apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: mysql-namespace  # Specify the namespace here
  labels:
    app: mysql
spec:
  replicas: 1  # Number of MySQL replicas
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-secret  # Reference the secret you created for ECR access
      containers:
        - name: mysql
          image: 911048994404.dkr.ecr.us-east-1.amazonaws.com/db_mysql:dbapp-latest  # Replace with your ECR image URL
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "passwors"  # Set the root password directly
            - name: MYSQL_DATABASE
              value: "employees"    # Database name
            - name: MYSQL_USER
              value: "root"         # Database user
            - name: MYSQL_PASSWORD
              value: "passwors"     # Set the user password directly
