apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-namespace  # Specify the namespace here
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
