apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: 911048994404.dkr.ecr.us-east-1.amazonaws.com/app:webapp-latest
      ports:
        - containerPort: 8080
