apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace  # Specify the namespace here
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Expose the application externally on this