apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-namespace  # Specify the namespace here
spec:
  replicas: 1  # Number of web application replicas
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: ecr-secret  # Reference the secret you created for ECR access
      containers:
        - name: webapp
          image: 911048994404.dkr.ecr.us-east-1.amazonaws.com/app:webapp-latest  # ECR image URL
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.mysql-namespace.svc.cluster.local"  # Fully qualified service name
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "passwors"  # Set the database password directly
            - name: DATABASE
              value: "employees"
            - name: APP_COLOR
              value: "lime"  # Default color
            - name: DBPORT
              value: "3306"  # MySQL default port
